config/routes.rb
Rails.application.routes.draw do
  root to: 'task_lists#index'

  devise_for :users

  resource :users, only: :show
  resources :task_lists do
    get 'favorited_task_lists', to: 'favorited_task_lists#update_favorited_task_list'
  end
  resources :favorited_task_lists, only: [:index]
  resources :tasks, only: [:edit, :update, :destroy] do
    get 'done', to: 'tasks#done'
    get 'pendant', to: 'tasks#pendant'
    resources :subtasks, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :subtasks, only: :destroy do
    get 'done', to: 'subtasks#done'
    get 'pendant', to: 'subtasks#pendant'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorited_task_list.rb
class FavoritedTaskList < ApplicationRecord
  belongs_to :user
  belongs_to :task_list
end

app/models/subtask.rb
class Subtask < ApplicationRecord
  belongs_to :task, inverse_of: :subtasks

  enum status: [ :pendant, :done ]

  validates :title, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :task_list, inverse_of: :tasks, optional: true
  has_many :subtasks, inverse_of: :task, dependent: :destroy

  enum status: [ :pendant, :done ]

  accepts_nested_attributes_for :subtasks, allow_destroy: true

  validates :title, presence: true, allow_blank: false

  after_update :broadcast_notification

  def broadcast_notification
    ActionCable.server.broadcast("notifications", {
      notification_partial: ApplicationController.renderer.render(
        partial: "task_lists/notifications",
        locals: { task_list: task_list }
      ),
      users_who_favorited: task_list.users_who_favorited
    })
  end

  def all_subtasks_done?
    subtasks.select(&:pendant?).empty?
  end

  def mark_subtasks
    subtasks.map(&:done!)
  end

  def unmark_subtasks
    subtasks.map(&:pendant!)
  end
end

app/models/task_list.rb
class TaskList < ApplicationRecord
  belongs_to :user
  has_many :tasks, inverse_of: :task_list, dependent: :destroy
  has_many :favorited_task_lists, dependent: :destroy

  enum status: [ :closed, :open ]

  accepts_nested_attributes_for :tasks, allow_destroy: true

  validates :title, presence: true

  after_update :broadcast_notification

  def broadcast_notification
    ActionCable.server.broadcast("notifications", {
      notification_partial: ApplicationController.renderer.render(
        partial: "task_lists/notifications",
        locals: { task_list: self }
      ),
      users_who_favorited: users_who_favorited
    })
  end

  def users_who_favorited
    FavoritedTaskList.where(task_list: self).map(&:user_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :task_lists, dependent: :destroy
  has_many :favorited_task_lists, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def favorited?(task_list)
    FavoritedTaskList.where(user_id: self.id, task_list_id: task_list.id).present?
  end

  def favorited_task_list(task_list)
    FavoritedTaskList.find_by(user: self, task_list: task_list)
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery
  before_action :authenticate_user!
end

app/controllers/favorited_task_lists_controller.rb
class FavoritedTaskListsController < ApplicationController
  before_action :set_task_list, only: :update_favorited_task_list

  def index
    @favorited_task_lists = FavoritedTaskList.includes(:task_list).where(user_id: current_user.id)
  end

  def update_favorited_task_list
    @favorited_task_list = current_user.favorited_task_list(@task_list)
    return @favorited_task_list.destroy if @favorited_task_list
    @favorited_task_list = FavoritedTaskList.new(task_list: @task_list)
    @favorited_task_list.user = current_user
    @favorited_task_list.save
  end

  private

  def set_task_list
    @task_list = TaskList.includes(:user, tasks: :subtasks).find(params[:task_list_id])
  end
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
  before_action :set_subtask, only: [:destroy, :done, :pendant]

  def destroy
    tasklist = @subtask.task.task_list
    task = @subtask.task
    @subtask.destroy
    task.done! if task.all_subtasks_done?
    respond_with @subtask, location: tasklist
  end

  def done
    @subtask.done!
    task = @subtask.task
    task.done! if task.all_subtasks_done?
    redirect_to @subtask.task.task_list
  end

  def pendant
    @subtask.pendant!
    @subtask.task.pendant!
    redirect_to @subtask.task.task_list
  end

  private

  def flash_interpolation_options
    { resource_name: @subtask.title }
  end

  def set_subtask
    id = params[:id] || params[:subtask_id]
    @subtask = Subtask.find(id)
  end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_action :set_task_list, only: [:show, :edit, :update, :destroy]

  def index
    @task_lists = TaskList.where(status: 'open')
  end

  def show
    @task_list = TaskListPresenter.new(@task_list, current_user)
  end

  def new
    @task_list = TaskList.new
    @task_list.tasks.build
  end

  def create
    @task_list = TaskList.new(task_list_params)
    @task_list.user = current_user
    if @task_list.save
      respond_with @task_list, location: @task_list
    else
      flash.now[:alert] = "Você deve preencher os campos marcados"
      render :new, alert: flash.now[:alert]
    end
  end

  def edit
    @task_list.tasks.build
  end

  def update
    if @task_list.update_attributes(task_list_params)
      respond_with @task_list, location: @task_list
    else
      @task_list.tasks.build
      render :edit
    end
  end

  def destroy
    @task_list.destroy
    respond_with @task_list, location: root_path
  end

  private

  def flash_interpolation_options
    { resource_name: @task_list.title }
  end

  def set_task_list
    @task_list = TaskList.includes(:tasks, tasks: :subtasks).find(params[:id])
  end

  def task_list_params
    params.require(:task_list).permit(:user_id, :title, :status, :task, tasks_attributes: [:id, :title, :task_list_id, :_destroy])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :done, :destroy, :pendant]

  def edit
    @task.subtasks.build
  end

  def update
    subtasks = @task.subtasks.count
    if @task.update_attributes(task_params)
      @task.pendant! unless subtasks == @task.subtasks.count
      respond_with @task, location: @task.task_list
    else
      @task.subtasks.build
      render :edit
    end
  end

  def done
    @task.done!
    @task.mark_subtasks
    redirect_to @task.task_list
  end

  def pendant
    @task.pendant!
    @task.unmark_subtasks
    redirect_to @task.task_list
  end


  def destroy
    task_list = @task.task_list
    @task.destroy
    respond_with @task, location: @task.task_list
  end

  private

  def flash_interpolation_options
    { resource_name: @task.title }
  end

  def set_task
    id = params[:id] || params[:task_id]
    @task = Task.find(id)
  end

  def task_params
    params.require(:task).permit(:title, :task_list_id, subtasks_attributes: [:id, :task_id, :_destroy, :title])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @private_task_lists = TaskList.where(user: current_user, status: 'closed')
    @public_task_lists = TaskList.where(user: current_user, status: 'open')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorited_task_lists_helper.rb
module FavoritedTaskListsHelper
end

app/helpers/subtasks_helper.rb
module SubtasksHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
  def link_to_add_row(name, f, association, **attrs)
    new_task = f.object.send(association).klass.new
    id = new_task.object_id
    fields = f.fields_for(association, new_task, child_index: id) do |t|
      render(association.to_s.singularize, f: t)
    end
    link_to(name, '#', class: "add_fields " + attrs[:class], data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorited_task_lists/index.html.erb
<div class="grey-wrapper">
  <div class="container">
    <h1 class="text-center">Listas de tarefas favoritas</h1>
    <div class="row">
      <% @favorited_task_lists.each do |favorited_task_list| %>
        <div class="col-xs-12 col-sm-6 col-md-3">
          <%= link_to task_list_path(favorited_task_list.task_list), class: 'task-list-card-link' do %>
            <div class="task-list-card">
              <div class="task-list-title text-center">
                <%= favorited_task_list.task_list.title %>
              </div>
              <div class="task-list-stats">
                <ul class="list-unstyled">
                  <li>
                    <%= favorited_task_list.task_list.tasks.count %> tarefas
                  </li>
                  <li>
                    <%= favorited_task_list.task_list.tasks.where(status: 'done').count %> tarefas completas
                  </li>
                </ul>
                <div class="favorited_task_list-box">
                  <%= link_to '<i class="glyphicon glyphicon-heart" aria-hidden="true" style="font-size: 20px;" ></i>'.html_safe, task_list_favorited_task_lists_path(favorited_task_list.task_list), remote: true, id: "favorited_task_list#{favorited_task_list.task_list.id}", class: "#{'favorited'if current_user.favorited?(favorited_task_list.task_list)}"  %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/favorited_task_lists/update_favorited_task_list.js.erb
$("#favorited_task_list<%= @task_list.id %>").toggleClass("favorited");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AutosegTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <div class="notifications"></div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
      App['notifications'] = App.cable.subscriptions.create(
        { channel: 'FavoritedChannel' },
        { received: (data) => {
            if (data.users_who_favorited.includes(<%= current_user.id if user_signed_in? %>)) {
              $('.notifications').append(data.notification_partial);
              setTimeout(() => {
                $('.notification-remove-tag').remove();
              }, 5000);
            }
          }
        }
      )
    </script>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= link_to root_path, class: 'navbar-brand' do %>
    <%= image_tag 'task_list', width: 40 %>
  <% end %>
  <div class="navbar-right">
    <% if user_signed_in? %>
      <%= link_to 'Nova lista de tarefas', new_task_list_path, class: "navbar-item navbar-link" %>
      <%= link_to 'Minhas listas', users_path, class: "navbar-item navbar-link" %>
      <%= link_to 'Favoritos', favorited_task_lists_path, class: "navbar-item navbar-link" %>
      <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: "navbar-item navbar-link" %>
    <% else %>
      <%= link_to 'Registrar-se', new_user_registration_path, class: "navbar-item navbar-link" %>
      <%= link_to 'Entrar', new_user_session_path, class: "navbar-item navbar-link" %>
    <% end %>
  </div>
</div>

app/views/shared/_task_list_card.html.erb
<div class="col-xs-12 col-sm-6 col-md-3">
  <%= link_to task_list_path(task_list), class: 'task-list-card-link' do %>
    <div class="task-list-card">
      <div class="task-list-title text-center">
        <%= task_list.title %>
      </div>
      <div class="task-list-stats">
        <ul class="list-unstyled">
          <li>
            <%= task_list.tasks.count %> tarefas
          </li>
          <li>
            <%= task_list.tasks.where(status: 'done').count %> tarefas completas
          </li>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="task-list-footer">
    <div class="favorited_task_list-box">
      <%= link_to '<i class="glyphicon glyphicon-heart" aria-hidden="true" style="font-size: 20px;" ></i>'.html_safe, task_list_favorited_task_lists_path(task_list), remote: true, id: "favorited_task_list#{task_list.id}", class: "#{'favorited'if current_user.favorited?(task_list)}"  %>
    </div>
  </div>
</div>

app/views/task_lists/_form.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="form-container">
        <h3>Lista de tarefas</h3>
        <%= form_for @task_list do |f| %>
          <div class="field task-list-title">
            <%= f.text_field :title, placeholder: 'Título da lista de tarefas', class: 'form-control' %>
          </div>

          <div class="field task-list-content">
            <div class="public">
              <%= f.radio_button :status, "open" %>
              <%= f.label :status, "Pública", value: "open"  %>
            </div>
            <br>
            <div class="private">
              <%= f.radio_button :status, "closed" %>
              <%= f.label :status, "Privada", value: "closed" %>
            </div>
          </div>

          <div class="fields">
            <%= f.fields_for :tasks do |t| %>
              <%= render 'task', f: t %>
            <% end %>
          </div>

          <div class="actions">
            <%= link_to_add_row('Adicionar tarefa', f, :tasks, class: 'btn btn-primary margin-btn btn-block') %>
            <%= f.submit class: 'btn btn-block btn-primary' %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/task_lists/_notifications.html.erb
<%= link_to task_list_path(task_list), class: 'notification-remove-tag' do %>
  <div class="notification-card">
    <p>Sua lista favoritada '<%= task_list.title %>' foi atualizada, clique para ver!</p>
  </div>
<% end %>

app/views/task_lists/_owned_task.html.erb
<%= link_to '<span class="glyphicon glyphicon-ok"></span>'.html_safe, task_done_path(task) %>
<%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, task_path(task), method: :delete %>

app/views/task_lists/_subtask_done_links.html.erb
<%= link_to '<span class="glyphicon glyphicon-unchecked"></span>'.html_safe, subtask_pendant_path(subtask) %>
<%= link_to '<span class="glyphicon glyphicon-trash" style="font-size: 15px;"></span>'.html_safe, subtask_path(subtask), method: :delete %>

app/views/task_lists/_subtask_links.html.erb
<%= link_to '<span class="glyphicon glyphicon-ok"></span>'.html_safe, subtask_done_path(subtask) %>
<%= link_to '<span class="glyphicon glyphicon-trash" style="font-size: 15px;"></span>'.html_safe, subtask_path(subtask), method: :delete %>

app/views/task_lists/_subtask_pendant_links.html.erb
<%= link_to '<span class="glyphicon glyphicon-check"></span>'.html_safe, subtask_done_path(subtask) %>
<%= link_to '<span class="glyphicon glyphicon-trash" style="font-size: 15px;"></span>'.html_safe, subtask_path(subtask), method: :delete %>

app/views/task_lists/_task.html.erb
<div class="task">
  <%= f.text_field :title, placeholder: 'Título da tarefa', label: false, class: 'form-control' %>
  <%= f.hidden_field :_destroy, as: :hidden %>
  <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, '#', class: 'remove-task' %>
</div>

app/views/task_lists/_task_done_links.html.erb
<%= link_to '<span class="glyphicon glyphicon-unchecked"></span>'.html_safe, task_pendant_path(task) %>
<%= link_to '<span class="glyphicon glyphicon-plus"></span>'.html_safe, edit_task_path(task) %>
<%= link_to '<span class="glyphicon glyphicon-trash""></span>'.html_safe, task_path(task), method: :delete %>

app/views/task_lists/_task_pendant_links.html.erb
<%= link_to '<span class="glyphicon glyphicon-check"></span>'.html_safe, task_done_path(task) %>
<%= link_to '<span class="glyphicon glyphicon-plus"></span>'.html_safe, edit_task_path(task) %>
<%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, task_path(task), method: :delete %>

app/views/task_lists/edit.html.erb
<%= render 'form' %>

app/views/task_lists/index.html.erb
<div class="grey-wrapper">
  <div class="container">
    <h1 class="text-center">Listas de tarefas públicas</h1>
    <div class="row">
      <% @task_lists.each do |task_list| %>
        <%= render 'shared/task_list_card', task_list: task_list %>
      <% end %>
    </div>
  </div>
</div>

app/views/task_lists/new.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="form-container">
        <h3>Nova lista de tarefas</h3>
        <%= form_for @task_list do |f| %>

          <div class="field">
            <%= f.label :status, "Pública", value: "open"  %>
            <%= f.radio_button :status, "open" %>
            <%= f.label :status, "Privada", value: "closed" %>
            <%= f.radio_button :status, "closed", checked: true %>
          </div>

          <div class="actions">
            <%= f.submit 'Criar lista de tarefas', class: 'btn btn-block btn-primary' %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/task_lists/show.html.erb
<div class="container">
  <div class="task-list-header text-center">
    <h1>
      <%= @task_list.title %>
      <%= link_to '<span class="glyphicon glyphicon-edit" style="font-size: 30px;"></span>'.html_safe, edit_task_list_path(@task_list) if @task_list.user == @current_user %>
      <%= link_to '<span class="glyphicon glyphicon-plus" style="font-size: 30px;"></span>'.html_safe, edit_task_list_path(@task_list) if @task_list.user == @current_user %>
      <%= link_to '<span class="glyphicon glyphicon-trash" style="font-size: 30px;"></span>'.html_safe, task_list_path(@task_list), method: :delete if @task_list.user == @current_user %>
      <span class="favorited_task_list">
        <%= link_to '<i class="glyphicon glyphicon-heart" aria-hidden="true" style="font-size: 35px;" ></i>'.html_safe, task_list_favorited_task_lists_path(@task_list), remote: true, id: "favorited_task_list#{@task_list.id}", class: "#{'favorited' if current_user.favorited?(@task_list)}" %>
      </span>
    </h1>
  </div>
  <div class="tasks-wrapper">
    <div class="row">
      <% @task_list.tasks.each do |task| %>
        <div class="col-md-6 col-md-offset-3">
          <div class="task-wrapper">
            <div class="task <%= 'task-done' if task.done? %>">
              <div class="task-title">
                <p><%= task.title %></p>
              </div>
              <div class="task-links">
                <%= (render @task_list.task_links(task), task: task) if @task_list.user == current_user %>
              </div>
            </div>
            <% task.subtasks.each do |subtask| %>
              <div class="subtask <%= 'subtask-done' if subtask.done? %>">
                <div class="task-title">
                  <p><%= subtask.title %></p>
                </div>
                <div class="subtask-links">
                  <%= (render @task_list.subtask_links(subtask), subtask: subtask) if @task_list.user == current_user %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/_subtask.html.erb
<div class="task">
  <%= f.hidden_field :_destroy, as: :hidden %>
  <%= f.text_field :title, placeholder: 'Título da subtarefa', class: 'form-control' %>
  <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, '#', class: 'remove-task' %>
</div>

app/views/tasks/edit.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="form-container">
        <h3>Tarefas</h3>
        <%= form_for @task do |f| %>
          <div class="field task-list-title">
            <%= f.text_field :title, placeholder: 'Título da tarefa', class: 'form-control' %>
          </div>

          <div class="fields">
            <%= f.fields_for :subtasks do |t| %>
              <%= render 'subtask', f: t %>
            <% end %>
          </div>

          <div class="actions">
            <%= link_to_add_row('Adicionar subtarefa', f, :subtasks, class: 'btn btn-primary margin-btn btn-block') %>
            <%= f.submit class: 'btn btn-block btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="title text-center">
    <h1>Minhas listas de tarefas</h1>
  </div>
  <div class="wrapper">
    <div class="row">
      <div class="col-xs-12">
        <h2>Privadas</h2>
        <% @private_task_lists.each do |task_list| %>
          <%= render 'shared/task_list_card', task_list: task_list %>
        <% end %>
      </div>

      <div class="col-xs-12">
        <h2>Públicas</h2>
        <% @public_task_lists.each do |task_list| %>
          <%= render 'shared/task_list_card', task_list: task_list %>
        <% end %>
      </div>
    </div>
  </div>
</div>